# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DisableCheckoutPersistCredentials < Formula
  desc "Disable actions/checkout's persist-credentials
"
  homepage "https://github.com/suzuki-shunsuke/disable-checkout-persist-credentials"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/disable-checkout-persist-credentials/releases/download/v0.1.0/disable-checkout-persist-credentials_darwin_amd64.tar.gz"
      sha256 "4140d1a0ed63563aa74731798b15694145ea5e13411789f609875846aebcacff"

      def install
        bin.install "disable-checkout-persist-credentials"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suzuki-shunsuke/disable-checkout-persist-credentials/releases/download/v0.1.0/disable-checkout-persist-credentials_darwin_arm64.tar.gz"
      sha256 "833343886bdb38ca10995642f031c1c4e42325ab7a5ab7950a2027aeacc86465"

      def install
        bin.install "disable-checkout-persist-credentials"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/disable-checkout-persist-credentials/releases/download/v0.1.0/disable-checkout-persist-credentials_linux_amd64.tar.gz"
        sha256 "93cef4a062f1f72a21ca9d722511749f5d53c34aa923dfbc7fbe1a1a2d7f41cc"

        def install
          bin.install "disable-checkout-persist-credentials"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/disable-checkout-persist-credentials/releases/download/v0.1.0/disable-checkout-persist-credentials_linux_arm64.tar.gz"
        sha256 "0968ad58c380702f8558ebb6b8489999bdbb6d3b4ee59c5aa6ebcc5382abbde2"

        def install
          bin.install "disable-checkout-persist-credentials"
        end
      end
    end
  end

  test do
    system "#{bin}/disable-checkout-persist-credentials --version"
  end
end
