# This file was generated by GoReleaser. DO NOT EDIT.
cask "disable-checkout-persist-credentials" do
  desc "Disable actions/checkout's persist-credentials
"
  homepage "https://github.com/suzuki-shunsuke/disable-checkout-persist-credentials"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "disable-checkout-persist-credentials"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/disable-checkout-persist-credentials/releases/download/v0.1.3/disable-checkout-persist-credentials_darwin_amd64.tar.gz"
      sha256 "6d28ffad6382a46bd0a6fdd6d90112d50aa16efe39f61a0c792b81072b72daad"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/disable-checkout-persist-credentials/releases/download/v0.1.3/disable-checkout-persist-credentials_darwin_arm64.tar.gz"
      sha256 "48c11e4b7b99e82410c6368adbff5c3ecd4489bcbef12a04506cb046a4d62cc4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/disable-checkout-persist-credentials/releases/download/v0.1.3/disable-checkout-persist-credentials_linux_amd64.tar.gz"
      sha256 "de8aa395d72a0ee5f96ae2e06a227b82c452efc94af92959b419ac0ca2f3632d"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/disable-checkout-persist-credentials/releases/download/v0.1.3/disable-checkout-persist-credentials_linux_arm64.tar.gz"
      sha256 "d8594d68c3c0a31ed3c687591f7e6e09ba62d4e0f7d750044c31e3039286aba2"
    end
  end

  # No zap stanza required
end
