# This file was generated by GoReleaser. DO NOT EDIT.
cask "disable-checkout-persist-credentials" do
  name "disable-checkout-persist-credentials"
  desc "Disable actions/checkout's persist-credentials
"
  homepage "https://github.com/suzuki-shunsuke/disable-checkout-persist-credentials"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "disable-checkout-persist-credentials"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/disable-checkout-persist-credentials/releases/download/v#{version}/disable-checkout-persist-credentials_darwin_amd64.tar.gz"
      sha256 "304e83bb3d31479192d7392cd2f09140cb3dd0356cbbb417399200cbc547f9eb"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/disable-checkout-persist-credentials/releases/download/v#{version}/disable-checkout-persist-credentials_darwin_arm64.tar.gz"
      sha256 "48ea9e0aa93febcc4d88095594fe38deb634292f9ed9b187e23067d50c4b4b43"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/disable-checkout-persist-credentials/releases/download/v#{version}/disable-checkout-persist-credentials_linux_amd64.tar.gz"
      sha256 "81a4e471cdf0788ad14f648a126d3a8ca82019026262fdfeeea5aaf6490fb89a"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/disable-checkout-persist-credentials/releases/download/v#{version}/disable-checkout-persist-credentials_linux_arm64.tar.gz"
      sha256 "a0925ca95870ad1f4bbdbb4e96172c4730558de76ac67f2d78f2ced1300ab9c7"
    end
  end

  # No zap stanza required
end
